### PR TITLE
Fix build failure on clang 16: turn off incompatible-function-pointer-types

### PR DESCRIPTION
**Pull request by Endle**
This PR is a workaround for https://github.com/Koka/gettext-rs/issues/114

### CODE REVIEW

**Comment by Endle** [comment]
@Minoru Can you have a review? Thank you

**Comment by crab2313** [comment]
This does not work on latest MacOS. The output of `clang --version`:

```
❯ clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by crab2313** [comment]
> @crab2313 can you share your log?

Nothing special. Clang of MacOS SDK prints different format of version string. So this implementation simply can't get the version of clang.

**Comment by Endle** [comment]
Thank you for pointing out! I see why it's failing now. I'll do a quick fix to it later

**Comment by Minoru** [comment]
Thanks! However, I don't want to add a dependency on `regex` just for this. I'll make an alternative PR where the warning is disabled unconditionally, and see what CI thinks about it.

**Comment by crab2313** [comment]
> Thanks! However, I don't want to add a dependency on `regex` just for this. I'll make an alternative PR where the warning is disabled unconditionally, and see what CI thinks about it.

Why not simply update to gettext 0.22.5 which solve this issue too.

**Comment by Minoru** [comment]
Because I want to move away from tarballs for #12, but that might take time, so I'll push a smaller release before that.

**Pull request closed without merging**
